spring:
  application:
    name: demo

bird:
  redis:
    enable: true
    key-group: dev:demo
    single:
      host: 127.0.0.1:6379
  zk:
    enable: true
    group: dev/demo
    address: 127.0.0.1:2181
    connection-timeout: 10000
    session-timeout: 30000

logging:
  config: classpath:logback.xml
