version: '3'
services:
  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    networks:
      - default
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /Users/master/Data/mysql/conf:/etc/mysql/conf.d
      - /Users/master/Data/mysql/data:/var/lib/mysql
    networks:
      - default
  zk:
    image: zookeeper:3.6
    container_name: zk
    ports:
      - "2181:2181"
    environment:
      TZ: Asia/Shanghai
    networks:
      - default
  nginx:
    image: nginx:1.17
    container_name: nginx
    ports:
      - "80:80"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /Users/master/Data/nginx/html:/usr/share/nginx/html
      - /Users/master/Data/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - disconf
  disconf:
    image: tomcat:jdk8
    container_name: disconf
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
    networks:
      - default
    volumes:
      - /Users/master/IdeaProjects/disconf/disconf-web/target/disconf-web:/usr/local/tomcat/webapps/ROOT
    depends_on:
      - mysql
      - redis
      - zk

networks:
  default:

